import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

const root = process.cwd();
const dist = resolve(root, "dist");
let html = await readFile(resolve(dist, "index.html"), "utf8");

const scriptPattern = /<script([^>]*)src="\.\/([^\"]+)"([^>]*)><\/script>/g;
for (const match of [...html.matchAll(scriptPattern)]) {
  const js = await readFile(resolve(dist, match[2]), "utf8");
  html = html.replace(match[0], `<script>${js}</script>`);
}

const stylePattern = /<link([^>]*)rel="stylesheet"([^>]*)href="\.\/([^\"]+)"([^>]*)>/g;
for (const match of [...html.matchAll(stylePattern)]) {
  const css = await readFile(resolve(dist, match[3]), "utf8");
  html = html.replace(match[0], `<style>${css}</style>`);
}

if (/src="\.\/|href="\.\/assets\//.test(html)) {
  throw new Error("generated HTML still contains external Vite asset references");
}
if (html.includes(")ROWEB\"")) {
  throw new Error("HTML collides with C++ raw-string delimiter");
}

const header = `#pragma once\n\n// Generated by web/scripts/embed.mjs. Do not hand-edit.\nnamespace ro::net::web_assets {\ninline constexpr char INDEX_HTML[] = R\"ROWEB(${html})ROWEB\";\n}\n`;
await writeFile(resolve(root, "../components/ro_network/include/ro/web_assets.hpp"), header);
console.log(`embedded ${Buffer.byteLength(html)} bytes of web UI`);
