#!/usr/bin/env bash
set -euo pipefail

build_dir="${1:-build}"
out_dir="${2:-firmware-artifact}"

require_file() {
  if [[ ! -f "$1" ]]; then
    echo "Required firmware file is missing: $1" >&2
    exit 1
  fi
}

require_file "$build_dir/ro_controller.bin"
require_file "$build_dir/bootloader/bootloader.bin"
require_file "$build_dir/partition_table/partition-table.bin"
require_file "$build_dir/flash_args"
require_file "$build_dir/flasher_args.json"

rm -rf "$out_dir"
mkdir -p "$out_dir/bootloader" "$out_dir/partition_table"

cp "$build_dir/ro_controller.bin" "$out_dir/"
cp "$build_dir/bootloader/bootloader.bin" "$out_dir/bootloader/"
cp "$build_dir/partition_table/partition-table.bin" "$out_dir/partition_table/"
cp "$build_dir/flash_args" "$out_dir/"
cp "$build_dir/flasher_args.json" "$out_dir/"

if [[ -f "$build_dir/ota_data_initial.bin" ]]; then
  cp "$build_dir/ota_data_initial.bin" "$out_dir/"
fi

cat > "$out_dir/FLASHING.txt" <<'EOF'
RO Controller - ESP32-S3 flash bundle

Requirements:
  python -m pip install --upgrade esptool

From this extracted directory, replace PORT with your serial port and run:
  python -m esptool --chip esp32s3 -p PORT -b 460800 --before default_reset --after hard_reset write_flash @flash_args

macOS example:
  python -m esptool --chip esp32s3 -p /dev/cu.usbmodemXXXX -b 460800 --before default_reset --after hard_reset write_flash @flash_args

Linux example:
  python -m esptool --chip esp32s3 -p /dev/ttyACM0 -b 460800 --before default_reset --after hard_reset write_flash @flash_args

The address/file mapping is generated by ESP-IDF 6.0.2 and is also available in flasher_args.json.
Do not flash the bench-test build to the installed controller; this bundle is the production build.
EOF

(
  cd "$out_dir"
  sha256sum \
    bootloader/bootloader.bin \
    partition_table/partition-table.bin \
    ro_controller.bin \
    > SHA256SUMS.txt
  if [[ -f ota_data_initial.bin ]]; then
    sha256sum ota_data_initial.bin >> SHA256SUMS.txt
  fi
  sha256sum -c SHA256SUMS.txt
)

echo "Firmware bundle created at $out_dir"
